zip-creator: add script no-force-encrypt and no-dm-verity

diff --git a/zip-creator/base/META-INF/com/google/android/update-binary b/zip-creator/base/META-INF/com/google/android/update-binary
--- a/zip-creator/base/META-INF/com/google/android/update-binary
+++ b/zip-creator/base/META-INF/com/google/android/update-binary
@@ -124,34 +124,60 @@ fi;
 # Ramdisk patches
 ##########################################################################################
 
-[ -z $KEEPVERITY ] && KEEPVERITY=false
-
-if [ -f /tmp/anykernel/dtb ]; then
-  ui_print "Found dtbo image"
-  ui_print " "
-  [ -z $KEEPVERITY ] && KEEPVERITY=true
+if [ "$3" ]; then
+	zip=$3
+	console=/proc/$$/fd/$2
+	# write the location of the console buffer to /tmp/console for other scripts to use
+	echo "$console" > /tmp/console
+else
+	console=$(cat /tmp/console)
+	[ "$console" ] || console=/proc/$$/fd/1
 fi
 
-if [ -z $KEEPFORCEENCRYPT ]; then
-  if [ "`getprop ro.crypto.state`" = "encrypted" ]; then
-    KEEPFORCEENCRYPT=true
-    ui_print "Encrypted data detected"
-    ui_print " "
-  else
-    KEEPFORCEENCRYPT=false
-  fi
-fi
+print() {
+	if [ "$1" ]; then
+		echo "ui_print $1" > "$console"
+	else
+		echo "ui_print  " > "$console"
+	fi
+	echo
+}
 
-if [ $KEEPVERITY ] && [ -f /tmp/anykernel/dtb ]; then
-  ./tmp/anykernel/magiskboot --dtb-patch dtb
-  ui_print "Patching fstab in dtb to remove dm-verity"
-  ui_print " "
-fi
+abort() {
+	[ "$1" ] && {
+		print "Error: $1"
+		print "Aborting..."
+	}
+	print "Failed to patch boot image!"
+}
 
-# skip_initramfs -> want_initramfs
-./tmp/anykernel/magiskboot --hexpatch kernel \
-736B69705F696E697472616D6673 \
-77616E745F696E697472616D6673
+cleanup() {
+	[ "$zip" ] && rm /tmp/console
+	umount /system
+}
+
+extract() {
+	rm -rf "$2"
+	mkdir -p "$2"
+	unzip -o "$1" -d "$2" || abort "Failed to extract zip to $2!"
+}
+
+setperm() {
+	find "$3" -type d -exec chmod "$1" {} \;
+	find "$3" -type f -exec chmod "$2" {} \;
+}
+
+
+
+if [ -f /tmp/anykernel/patch/010-no-force-encrypt ] || [ -f /tmp/anykernel/patch/015-no-dm-verity ]; then
+	$bb chmod -R 755 /tmp/anykernel/ramdisk;
+	find /tmp/anykernel/patch/ -type f | sort > patchfiles
+	while read -r patchfile; do
+		ui_print "Executing: $(basename "$patchfile")"
+		env="/tmp/anykernel/patch/" sh "$patchfile" ||
+			ui_print "Script failed: $(basename "$patchfile")"
+	done < patchfiles
+fi
 
 mount -o rw,remount -t auto /cache;
 rm -f /cache/*;
